name: Build and Run

on:
  push: # Trigger the workflow on any branch push
    branches:
      - '*' # Run this workflow on any branch that pushes an update

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
      
      - name: Format code
        run: dotnet format -v d

      - name: Restore dependencies
        run: dotnet restore
